# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd14bddb137c9cd7e55d65c98f1d5c3bbc20fbc9aad9b20e9d07a026a6f19380d10b23b34a33c063778388fa0c95eb966e7b54a19e706832ec01398f621e3ce

test:
  secret_key_base: 56e8fa3fb5557832b310324199f5324b16e2a8692f697f429f009f687f32f0c4fd72f8b02c8869e4fc344def219ef11f120b1b07dfaa1e34d17e08b6e578f021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
